spring:
  redis:
    host: 192.168.0.123
    port: 6379
    password: unidatacache@2013
  datasource:
    url: jdbc:mysql://192.168.0.215:3306/courseschedule2?serverTimezone=Asia/Shanghai
    username: jyjyoa
    password: jyjyoa
  jpa:
    hibernate:
      ddl-auto: update
